//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""TimingMG_AM"",
            ""id"": ""75c2fa6e-9697-4aed-b891-08bfa461f06d"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""f350e3c2-a7cd-42a2-a39b-c5661a17eb5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d86b0e4a-6d46-4ffd-aa27-ae31ef5c2561"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TimingMG_AM
        m_TimingMG_AM = asset.FindActionMap("TimingMG_AM", throwIfNotFound: true);
        m_TimingMG_AM_Newaction = m_TimingMG_AM.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TimingMG_AM
    private readonly InputActionMap m_TimingMG_AM;
    private List<ITimingMG_AMActions> m_TimingMG_AMActionsCallbackInterfaces = new List<ITimingMG_AMActions>();
    private readonly InputAction m_TimingMG_AM_Newaction;
    public struct TimingMG_AMActions
    {
        private @PlayerInputActions m_Wrapper;
        public TimingMG_AMActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_TimingMG_AM_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_TimingMG_AM; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TimingMG_AMActions set) { return set.Get(); }
        public void AddCallbacks(ITimingMG_AMActions instance)
        {
            if (instance == null || m_Wrapper.m_TimingMG_AMActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TimingMG_AMActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(ITimingMG_AMActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(ITimingMG_AMActions instance)
        {
            if (m_Wrapper.m_TimingMG_AMActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITimingMG_AMActions instance)
        {
            foreach (var item in m_Wrapper.m_TimingMG_AMActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TimingMG_AMActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TimingMG_AMActions @TimingMG_AM => new TimingMG_AMActions(this);
    public interface ITimingMG_AMActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
